import HeaderBar from './Headerbar';
import Input from './CustomTextInput';
import CustomDateTimeInput from './DateTimeInput';
import CustomPickerInput from './PickerInput';
import Drawer from './Drawer';
import LinearGradientButton from './LinearGradientButton';
import LinearGradientWrapper from './LinearGradient';
import CircularProgressBar from './CircularProgressBar';
import SemiCircularProgressBar from './SemicircularProgressBar';
import DropButton from './DropDownButton';
import ModalComponent from './Modal';
import MultiSelectModal from './MultiSelectModal';
import ProfileComponent from './ProfileComponent';
import LoadingComponent from './Loading';

export const TextInput = Input;
export const Header = HeaderBar;
export const DateTimeInput = CustomDateTimeInput;
export const PickerInput = CustomPickerInput;
export const DrawerView = Drawer;
export const LinearButton = LinearGradientButton;
export const LinearGradient = LinearGradientWrapper;
export const CircularBar = CircularProgressBar;
export const SemiCircularBar = SemiCircularProgressBar;
export const DropDownButton = DropButton;
export const Modal = ModalComponent;
export const MultiSelect = MultiSelectModal;
export const ProfileComp = ProfileComponent;
export const Loading = LoadingComponent;
