export const Constants = {
  //Modes [UAT, PROD]
  SET_ADDRESS: 'SET_ADDRESS',
  RESET_ADDRESS: 'RESET_ADDRESS',
  SET_AUTHKEY: 'SET_AUTHKEY',
  LOGOUT: 'LOGOUT',
  REGISTER: 'REGISTER',
  SET_DATA: 'SET_DATA',
  SET_PROFILE: 'SET_PROFILE',
  REMOVE_PROFILE: 'REMOVE_PROFILE',
};
