export const Constants = {
  //Modes [UAT, PROD]
  SET_ADDRESS: 'SET_ADDRESS',
  RESET_ADDRESS: 'RESET_ADDRESS',
  SET_AUTHKEY: 'SET_AUTHKEY',
  LOGOUT: 'LOGOUT',
  REGISTER: 'REGISTER',
  SET_DATA: 'SET_DATA',
  SET_PROFILE: 'SET_PROFILE',
  REMOVE_PROFILE: 'REMOVE_PROFILE',
  FETCH_LIKES: 'FETCH_LIKES',
  FETCH_BLOCK: 'FETCH_BLOCK',
  CREATE_ROOM: 'CREATE_ROOM',
  SEND_MSG: 'SEND_MSG',
  GET_CONVERSATION: 'GET_CONVERSATION',
  CHANGE_STATUS: 'CHANGE_STATUS',
  READ_CHAT: 'READ_CHAT'
};
