export const Constants = {
  //Modes [UAT, PROD]
  SET_ADDRESS: 'SET_ADDRESS',
  RESET_ADDRESS: 'RESET_ADDRESS',
  SET_AUTHKEY: 'SET_AUTHKEY',
  LOGOUT: 'LOGOUT',
  REGISTER: 'REGISTER',
  SET_DATA: 'SET_DATA',
  SET_PROFILE: 'SET_PROFILE',
  REMOVE_PROFILE: 'REMOVE_PROFILE',
  FETCH_LIKES: 'FETCH_LIKES',
  FETCH_LIKES_RECEIVED: 'FETCH_LIKES_RECEIVED',
  FETCH_BLOCK: 'FETCH_BLOCK',
  GET_CONVERSATION: 'GET_CONVERSATION',
  GET_CONVERSATION_REQUESTED: 'GET_CONVERSATION_REQUESTED',
  GET_CONVERSATION_DECLINED: 'GET_CONVERSATION_DECLINED',
};
